// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_default3 = "CgkIk-b9xt0FEAIQAw"; // <GPGSID>
        public const string achievement_default1 = "CgkIk-b9xt0FEAIQAQ"; // <GPGSID>
        public const string achievement_default5 = "CgkIk-b9xt0FEAIQBQ"; // <GPGSID>
        public const string leaderboard_default = "CgkIk-b9xt0FEAIQBg"; // <GPGSID>
        public const string achievement_default4 = "CgkIk-b9xt0FEAIQBA"; // <GPGSID>
        public const string achievement_default2 = "CgkIk-b9xt0FEAIQAg"; // <GPGSID>

}

